Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y ubuntu-desktop
      sudo apt-get install -y chef-solo
      if ! command -v chef-solo >/dev/null 2>&1; then
        sudo apt-get install -y chef-solo
        echo "Chef installed successfully."
      else
        echo "Chef is already installed."
      fi
      sudo apt-get update
      if ! command -v wireshark >/dev/null 2>&1; then
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wireshark
        sudo dpkg-reconfigure -f noninteractive wireshark-common
        sudo usermod -a -G wireshark $USER
        echo "Wireshark installed successfully."
      else
        echo "Wireshark is already installed. Version: $(wireshark --version)"
      fi
    SHELL
    vm1.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "wireshark"
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "forwarded_port", guest: 80, host: 8090
    vm2.vm.network "private_network", ip: "192.168.33.20"
    vm2.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
    end
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y ubuntu-desktop
      sudo apt-get update
      if ! command -v wireshark >/dev/null 2>&1; then
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wireshark
        sudo dpkg-reconfigure -f noninteractive wireshark-common
        sudo usermod -a -G wireshark $USER
        echo "Wireshark installed successfully."
      else
        echo "Wireshark is already installed. Version: $(wireshark --version)"
      fi
    SHELL
  end
end