Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "2048"
    end

    config.vm.define "VM_Chef_Market" do |vm|
        vm.vm.network "forwarded_port", guest: 80, host: 8080
        vm.vm.network "private_network", ip: "192.168.33.10"
        vm.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y ubuntu-desktop
            sudo apt-get install -y nginx # Ensure nginx is installed
            sudo /opt/chef/embedded/bin/gem install kitchen-vagrant
            # Install Chef using the Omnibus Installer
            curl -L https://omnitruck.chef.io/install.sh | sudo bash
        SHELL
        vm.vm.provision "chef_solo" do |chef|
            chef.add_recipe "chef-market::default"
            chef.add_recipe "chef-market::kitchen_install" # Add this line
        end
    end
end